# -*- coding: utf-8 -*-
# -*- find-file-hook: org-babel-execute-buffer -*-

#+TITLE: Starter Kit Latex-Org combination
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:starter-kit.org][Emacs Starter Kit]].

* Starter Kit Latex-Org combination

I've always been troubled by the fact that I sometimes want to work in pure Latex and sometimes in XeLaTeX.
My default is XeLatex. If I want to change it to LaTeX (maybe it is really pdflatex), then change the default [[engine]]. 
And if I am working with org-mode, I also have to change the [[export]] option and comment out the XeLaTeX [[options]].

To simplify things I have created two routes in this document. By commenting out the one I don't want, and compiling this document, I will have =xelatex= or =pdflatex= in action. 

** How to use 
1. Comment the engine you don't want to use. 
2. Delete =starter-kit-latex-org.el=
3. Evaluate the following:

#+BEGIN_EXAMPLE
(starter-kit-load "starter-kit-latex-org.org")
#+END_EXAMPLE

4. Use the export facility of org and it should be fine.
   - REMEMBER: include =#+LaTeX_CLASS: memarticle= if using /XeLaTeX/ and the standard org export. This way I'll have the Minion, Myriad and Pragmata fonts.
     + No need to include it if using the Pandoc export with the /XeLaTeX/ export.
 
** Use compilation default

The default set here does not matter much as I'm asked what command to run every time I run tex on a file. 

#+srcname: latemkdefault
#+begin_src emacs-lisp :tangle yes
    (eval-after-load "tex"
      '(add-to-list 'TeX-command-list '("latexmk" "latexmk -synctex=1 -shell-escape -pdf %s" TeX-run-TeX nil t :help "Process file with latexmk"))
      )
    (eval-after-load "tex"
      '(add-to-list 'TeX-command-list '("xelatexmk" "latexmk -synctex=1 -shell-escape -xelatex %s" TeX-run-TeX nil t :help "Process file with xelatexmk"))
      )

  (add-hook 'TeX-mode-hook '(lambda () (setq TeX-command-default "latexmk")))  
#+end_src

#+RESULTS: latemkdefault
| (lambda nil (setq TeX-command-default latexmk)) | pandoc-mode |

* COMMENT The /XeLaTeX/ route 
** Set default engine <<engine>>

Custom variables kludge. Why can't I get these to work via =setq=?
DGM: Originally this was at the end of =kjhealy.org=.
What if I don't set one by default?

Watch out! If I want to change to latex (instead of xelatex), and I have a =custom.el= file, then I have to get rid of this =custom.el= file

#+BEGIN_SRC emacs-lisp :tangle yes
;; (LaTeX-XeTeX-command "xelatex -synctex=1 -shell-escape")
(setq-default TeX-engine (quote xetex))
;; (custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 ;;'(LaTeX-XeTeX-command "xelatex -synctex=1 -shell-escape")
 ;;'(TeX-engine (quote xetex))
 ;; '(TeX-view-program-list (quote (("Skim" "/Applications/Skim.app/Contents/SharedSupport/displayline %n %o %b"))))
 ;; '(TeX-view-program-selection (quote (((output-dvi style-pstricks) "dvips and gv") (output-dvi "xdvi") (output-pdf "Skim") (output-html "xdg-open"))))
;; '(blink-cursor-mode nil)
;; '(text-mode-hook (quote (text-mode-hook-identify)))
;; )
#+END_SRC

#+RESULTS:
: xetex

** XeLaTeX and pdfLaTeX Org Export Settings 

    Configure org-mode to export directly to PDF using xelatex, compiling the bibliography as it goes, with my preferred setup in each case. There is a good deal of local stuff in this section. The required style files used below are available at https://github.com/kjhealy/latex-custom-kjh. You may need to adjust or remove some of these settings depending on your preferences and local configuration.

From https://github.com/kjhealy/emacs-starter-kit/blob/master/kjhealy.org

    #+source: orgmode-latex-export
    #+BEGIN_SRC emacs-lisp :tangle yes
    (require 'ox-latex)
    #+END_SRC

LaTeX compilation command. For orgmode docs we just always use xelatex for convenience. You can change it to pdflatex if you like, just remember to make the adjustments to the packages-alist below.
<<export>>

Also, if I change to latex instead of xelatex, then change tangle option to no or else latex will use xelatex options the compilation will fail. Update: it's enough if I comment out the following heading.

#+BEGIN_SRC emacs-lisp :tangle yes
(setq org-latex-pdf-process '("latexmk -pdflatex='xelatex -synctex=1 --shell-escape' -bibtex -pdf %f"))

;;  (setq org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f"))  ;; this is Kitchin's way

;; the alternative, if you want a regular pdflatex would be, I think
;; (setq org-latex-pdf-process '("latexmk -pdf %f"))
;; (setq org-latex-pdf-process '("latexmk -pdflatex='pdflatex --shell-escape -bibtex -f'  -pdf %f"))
#+END_SRC

#+RESULTS:
| latexmk -pdflatex='xelatex -synctex=1 --shell-escape' -bibtex -pdf %f |

*** XeLaTeX options (Comment out if default latex is used instead)  <<options>>

**** Listings and Minted

Choose either listings or minted for exporting source code blocks. Using minted (as here) requires pygments be installed. 
I don't tangle it now because I set the default to =minted= in =/home/dgm/texmf/tex/generic/latex-custom-kjh/needs-org-mode/org-preamble-xelatex.sty=

#+BEGIN_SRC emacs-lisp :tangle no
;;   (setq org-latexg-listings t)
  ;; and change references to "minted" below to "listings"
;;;;;;;;;;;;;;;;  (setq org-latex-listings 'minted)  ;; already included in =~/texmf/tex/generic/latex-custom-kjh/needs-org-mode/org-preamble-xelatex.sty=
#+END_SRC

Default settings for minted code blocks. =bg= will need to be defined in the preamble of your document. Now I don't use them and I don't see differences in the documents produced \dots Why?

#+BEGIN_SRC emacs-lisp :tangle no
;;(setq org-latex-minted-options
;;      '(;("frame" "single")
;;        ("bgcolor" "bg") 
;;        ("fontsize" "\\small")
;;        ))
#+END_SRC

My new option comes from here: https://emacs.stackexchange.com/questions/33010/how-to-word-wrap-within-code-blocks

A commonly used environment for source code is lstlisting, provided by the LaTeX package listings. To get Org-mode to use it, add it to org-latex-packages-alist and set the variable org-latex-listings to t:

And to then get listings to wrap, the breaklines=true option needs to be supplied to listings. Org-mode can do this:

#+BEGIN_SRC emacs-lisp :tangle no
(add-to-list 'org-latex-packages-alist '("" "listings" nil))
(setq org-latex-listings t)
(setq org-latex-listings-options '(("breaklines" "true")))
#+END_SRC

#+RESULTS:
| breaklines | true |

The equivalente in =minted= would be: 

#+BEGIN_EXAMPLE
(setq org-latex-minted-options '(("breaklines" "true")
                                 ("breakanywhere" "true")))
#+END_EXAMPLE

**** TOC 
Turn off the default toc behavior; deal with it properly in headers to files.

#+BEGIN_SRC emacs-lisp :tangle yes
(defun org-latex-no-toc (depth)  
  (when depth
      (format "%% Org-mode is exporting headings to %s levels.\n"
              depth)))
(setq org-latex-format-toc-function 'org-latex-no-toc)
#+END_SRC

#+RESULTS:
: org-latex-no-toc

Now I define the style of memoir-class articles and others. Note the insertion of the =\input= statement for the vc information 

#+BEGIN_SRC emacs-lisp :tangle yes
(add-to-list 'org-latex-classes
               '("memarticle"
                 "\\documentclass[11pt,oneside,article]{memoir}\n\%\input{vc} % vc package"
                  ("\\section{%s}" . "\\section*{%s}")
                  ("\\subsection{%s}" . "\\subsection*{%s}")
                  ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                  ("\\paragraph{%s}" . "\\paragraph*{%s}")
                  ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))

(add-to-list 'org-latex-classes
               '("membook"
                 "\\documentclass[11pt,oneside]{memoir}\n\%\input{vc} % vc package"
                 ("\\chapter{%s}" . "\\chapter*{%s}")
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")))
 #+END_SRC

 #+RESULTS:
 | membook | \documentclass[11pt,oneside]{memoir} |


Default packages included in the tex file. As before, =org-preamble-xelatex= is part of =latex-custom-kjh=. There's =org-preamble-pdflatex= as well, if you wish to use that instead.
DGM note: This code calls on the stuff in the =~/texmf= directory that allows using fonts a la MinionPro etc. Specifically, it uses the =org-preamble-xelatex= style file. 
DGM note on 13 may: I'ved tangled to no as this conflicted with my export to beamer. Now I have included these lines in the =org-skeleton= code.
Things I've learnt today that are key: =org export=  inputs a whole bunch of packages that maybe it's not what you wanted and some of them may conflict with packages you do want to have. To get rid of them you need =(setq org-latex-default-packages-alist nil)=

Then, if I uncomment the rest I'll have the call to =org-preamble-xelatex= in every latex file but it happens that this call is great for articles but not for beamer presentations. So I have disabled it here and I have added to the skeleton template. By the way, I also need a beamer skeleton!

#+BEGIN_SRC emacs-lisp :tangle yes
 (setq org-latex-default-packages-alist nil)     
;; (setq org-latex-packages-alist
;;        '(("minted" "org-preamble-xelatex" t)
;;          ("" "graphicx" t)
;;          ("" "longtable" nil)
;;          ("" "float" ))) 
   #+END_SRC

   #+RESULTS:

   #+RESULTS: orgmode-latex-export
   : ox-latex

* The /LaTeX/ route 
** Set default engine 

Custom variables kludge. Why can't I get these to work via =setq=?
DGM: Originally this was at the end of =kjhealy.org=.
What if I don't set one by default?

Watch out! If I want to change to latex (instead of xelatex), and I have a =custom.el= file, then I have to get rid of this =custom.el= file

#+BEGIN_SRC emacs-lisp :tangle yes
(setq-default TeX-engine (quote default))
;;(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
;; '(LaTeX-XeTeX-command "latex -synctex=1 -shell-escape")
;; '(TeX-engine (quote default))
 ;; '(TeX-view-program-list (quote (("Skim" "/Applications/Skim.app/Contents/SharedSupport/displayline %n %o %b"))))
 ;; '(TeX-view-program-selection (quote (((output-dvi style-pstricks) "dvips and gv") (output-dvi "xdvi") (output-pdf "Skim") (output-html "xdg-open"))))
;; '(blink-cursor-mode nil)
;; '(text-mode-hook (quote (text-mode-hook-identify)))
;; )
#+END_SRC

#+RESULTS:
: default

** LaTeX options 

Turn off the default toc behavior; deal with it properly in headers to files.

#+BEGIN_SRC emacs-lisp :tangle yes
(defun org-latex-no-toc (depth)  
  (when depth
      (format "%% Org-mode is exporting headings to %s levels.\n"
              depth)))
(setq org-latex-format-toc-function 'org-latex-no-toc)
#+END_SRC

#+RESULTS:
: org-latex-no-toc

*** Disable default list of packages

The reason is that my style files have a list of their own. If not, in  Beamer, for example, I got this list of packages automatically included:

#+BEGIN_EXAMPLE2
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{graphicx}
\usepackage{grffile}
\usepackage{longtable}
\usepackage{wrapfig}
\usepackage{rotating}
\usepackage[normalem]{ulem}
\usepackage{amsmath}
\usepackage{textcomp}
\usepackage{amssymb}
\usepackage{capt-of}
\usepackage{hyperref}
\usepackage{listings}
#+END_EXAMPLE

which then my style file duplicated.

#+BEGIN_SRC emacs-lisp :tangle yes
(setq org-latex-default-packages-alist nil)     
;; (setq org-latex-packages-alist
;;        '(("minted" "org-preamble-xelatex" t)
;;          ("" "graphicx" t)
;;          ("" "longtable" nil)
;;          ("" "float" ))) 
   #+END_SRC

   #+RESULTS:

*** Listings vs Minted for Code Higlighting
Originally the package =minted= was not working with /LaTeX/ even though it worked with /XeLaTeX/. I found the solution reading this https://emacs.stackexchange.com/questions/27982/export-code-blocks-in-org-mode-with-minted-environment

Now I've tangled it to "no" because I have created the =sanchez-dgm.sty= where I want to use =listings= and I think this code may interfere with it.

#+BEGIN_SRC emacs-lisp :tangle no
(setq org-latex-listings 'minted
      org-latex-default-packages-alist nil)     
(setq org-latex-packages-alist
        '(("minted" "org-preamble-pdflatex" t)
          ;;("" "graphicx" t)
          ;;("" "longtable" nil)
          ;;("" "float" )
          ))
   #+END_SRC

   #+RESULTS:
   | minted | org-preamble-pdflatex | t |

My new option comes from here: https://emacs.stackexchange.com/questions/33010/how-to-word-wrap-within-code-blocks

A commonly used environment for source code is lstlisting, provided by the LaTeX package listings. To get Org-mode to use it, add it to org-latex-packages-alist and set the variable org-latex-listings to t:

And to then get listings to wrap, the breaklines=true option needs to be supplied to listings. Org-mode can do this:

#+BEGIN_SRC emacs-lisp :tangle no
(add-to-list 'org-latex-packages-alist '("" "listings" nil))
(setq org-latex-listings t)
(setq org-latex-listings-options '(("breaklines" "true")))
#+END_SRC

#+RESULTS:
| breaklines | true |

The equivalente in =minted= would be: 

#+BEGIN_EXAMPLE
(setq org-latex-minted-options '(("breaklines" "true")
                                 ("breakanywhere" "true")))
#+END_EXAMPLE

** =pdfLaTeX= Org Export Settings 

    Configure org-mode to export directly to PDF using xelatex, compiling the bibliography as it goes, with my preferred setup in each case. There is a good deal of local stuff in this section. The required style files used below are available at https://github.com/kjhealy/latex-custom-kjh. You may need to adjust or remove some of these settings depending on your preferences and local configuration.

From https://github.com/kjhealy/emacs-starter-kit/blob/master/kjhealy.org


    #+source: orgmode-latex-export
    #+BEGIN_SRC emacs-lisp :tangle yes
    (require 'ox-latex)
    #+END_SRC

LaTeX compilation command. For orgmode docs we just always use xelatex for convenience. You can change it to pdflatex if you like, just remember to make the adjustments to the packages-alist below.
<<export>>

Also, if I change to latex instead of xelatex, then change tangle option to no or else latex will use xelatex options the compilation will fail. Update: it's enough if I comment out the following heading.

#+BEGIN_SRC emacs-lisp :tangle yes

;; (setq org-latex-pdf-process '("latexmk -pdflatex='pdflatex -synctex=1 --shell-escape -bibtex -f' -pdf %f")) ;; with this it doesn't work
;; (setq org-latex-pdf-process (list "latexmk -shell-escape -bibtex -f -pdf %f"))  ;; this is Kitchin's way
(setq org-latex-pdf-process (list "latexmk -synctex=1 -shell-escape -bibtex -f -pdf %f"))  ;; this is Kitchin's way customized

;; the alternative, if you want a regular pdflatex would be, I think
;; (setq org-latex-pdf-process '("latexmk -pdf %f"))
#+END_SRC

#+RESULTS:
| latexmk -synctex=1 -shell-escape -bibtex -f -pdf %f |

* Beamer

Taken from Sacha Chua's config files. 
Reading https://orgmode.org/worg/exporters/beamer/ox-beamer.html I think as of Orgmode 8.0.3 this setup is not necessary anymore.

Deleted:               "\\documentclass\[presentation\]\{beamer\}"
#+BEGIN_SRC emacs-lisp :tangle no
(with-eval-after-load 'org
  (require 'ox-latex)
  (add-to-list 'org-latex-classes
             '("beamer
               "\\documentclass\[xcolor=x11names,compress\]\{beamer\}"
               "\\mode<presentation> \{"
               "    \\usetheme\{Hannover\}"
               "    \\usecolortheme\{beaver\}" 
               "\}"
               ("\\section\{%s\}" . "\\section*\{%s\}")
               ("\\subsection\{%s\}" . "\\subsection*\{%s\}")
               ("\\subsubsection\{%s\}" . "\\subsubsection*\{%s\}"))))
#+END_SRC

#+RESULTS:
| beamer  | \documentclass[xcolor=x11names,compress]{beamer}\n | \mode<presentation> {\n | \usetheme{Hannover}\n | \usecolortheme{beaver}\n | }\n | (\section{%s} . \section*{%s}) | (\subsection{%s} . \subsection*{%s}) | (\subsubsection{%s} . \subsubsection*{%s}) |
| beamer  | \documentclass[xcolor=x11names,compress]{beamer}   | \mode<presentation> {   | \usetheme{Hannover}   | \usecolortheme{beaver}   | }   | (\section{%s} . \section*{%s}) | (\subsection{%s} . \subsection*{%s}) | (\subsubsection{%s} . \subsubsection*{%s}) |
| membook | \documentclass[11pt,oneside]{memoir}               |                         |                       |                          |     |                                |                                      |                                            |

Of course we need to load  =beamer= for it to show up in the menu after =C-c C-e=.
#+BEGIN_SRC emacs-lisp :tangle yes
(require 'ox-beamer)
#+END_SRC

#+RESULTS:
: ox-beamer

** =listings= with Beamer

#+BEGIN_SRC emacs-lisp :tangle yes
(with-eval-after-load 'ox-beamer 
  (add-to-list 'org-latex-packages-alist '("" "listings" nil))
  (setq org-latex-listings t)
  (setq org-latex-listings-options '(("breaklines" "true"))))
  #+END_SRC

  #+RESULTS:
  | breaklines | true |


* My =sty= file
DGM 3 nov 2019:  hey, I've noticed that now I don't have =org-preamble-pdflatex.sty= loaded by default when I export to latex!! Trying to fix it with this:

elisp: Note that when I did ='(("org-preamble-pdflatex" t)))= the =sty= "loaded" was =t.sty=. And if I did ='(("org-preamble-pdflatex")= I got the =nil.sty=... so I don't really know how =setq= works.

#+begin_src emacs-lisp :tangle yes
(setq org-latex-packages-alist
        '(( "" "org-preamble-pdflatex" nil)))
#+end_src

#+RESULTS:
|   | org-preamble-pdflatex | nil |


* org-export

From: https://orgmode.org/worg/org-tutorials/org-latex-export.html

#+BEGIN_SRC emacs-lisp :tangle yes
(defun org-export-latex-no-toc (depth)
    (when depth
      (format "%% Org-mode is exporting headings to %s levels.\n"
              depth)))
  (setq org-export-latex-format-toc-function 'org-export-latex-no-toc)
#+END_SRC

#+RESULTS:
: org-export-latex-no-toc

* Math notation in Latex in Org

From https://tex.stackexchange.com/questions/78501/change-size-of-the-inline-image-for-latex-fragment-in-emacs-org-mode and  https://www.youtube.com/watch?v=88Mid7B31YQ&list=PLKNjNbxhXaeA57E5uJldm-vW_qfxeF6Gy&index=3

Fuller explanation here https://www.reddit.com/r/emacs/comments/9h44lk/i_can_finally_preview_latex_in_orgmode_took_me/

and issue of foreground not working addressed here: https://emacs.stackexchange.com/questions/22607/background-color-of-latex-fragments-in-org-mode/44693#44693

This is what solved the issue in the end!!! 

or look for =change foreground in "org-format-latex-options"= in google.

#+BEGIN_SRC emacs-lisp :tangle yes
;; fix color handling in org-preview-latex-fragment
(let ((dvipng--plist (alist-get 'dvipng org-preview-latex-process-alist)))
  (plist-put dvipng--plist :use-xcolor t)
  (plist-put dvipng--plist :image-converter '("dvipng -D %D -T tight -o %O %f")))

;; bigger latex fragment
(setq org-format-latex-options (plist-put org-format-latex-options :scale 4))
(setq org-format-latex-options (plist-put org-format-latex-options :foreground "grey"))
;;(setq org-format-latex-options (plist-put org-format-latex-options :html-foreground "grey"))
;;(setq org-format-latex-options (plist-put org-format-latex-options :background "grey"))
#+END_SRC

#+RESULTS:
| :foreground | grey | :background | grey | :scale | 4 | :html-foreground | red | :html-background | Transparent | :html-scale | 1.0 | :matchers | (begin $1 $ $$ \( \[) |

Pending: how to change font locking for formulas with this preview. 

* Setting =hyperref= in org-mode

From https://emacs.stackexchange.com/questions/12878/how-to-change-style-of-hyperlinks-within-pdf-published-from-org-mode-document

By default, Org mode adds a rather unhelpful hypersetup section. You can prevent this addition by adding the following line to your .emacs file:

#+BEGIN_SRC emacs-lisp :tangle yes
(customize-set-value 'org-latex-with-hyperref nil)
#+END_SRC

#+RESULTS:

In addition, if you want to pass any options to hyperref or url (which is loaded
automically by hyperref), then you can use a command of the form (notice the escaped
backslash):

#+BEGIN_SRC emacs-lisp :tangle yes
(add-to-list 'org-latex-default-packages-alist "\\PassOptionsToPackage{hyphens}{url}")
#+END_SRC

* Provide

#+BEGIN_SRC emacs-lisp  :tangle yes
(provide 'starter-kit-latex-org)
#+END_SRC

* Final message
#+source: message-line
#+begin_src emacs-lisp :tangle yes
  (message "Starter Kit LaTeX-Org loaded.")
#+end_src

#+RESULTS: message-line
: Starter Kit LaTeX-Org loaded.

