# -*- coding: utf-8 -*-
# -*- find-file-hook: org-babel-execute-buffer -*-

#+TITLE: Starter Kit aspell
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:starter-kit.org][Emacs Starter Kit]].

* COMMENT Kieran Healy's Starter Kit aspell
Hackish file to accommodate having aspell installed on your Mac. Otherwise
flyspell doesn't start properly. Putting this customization in
<username>.org initiates it too late. 

- This file is loaded by a special line added to [[file:starter-kit.org][starter-kit.org]].


** COMMENT Specify aspell
#+begin_src emacs-lisp :tangle no
  (require 'flyspell)
  (setq ispell-program-name "aspell"
        ispell-dictionary "american"
        ispell-dictionary-alist
        (let ((default '("[A-Za-z]" "[^A-Za-z]" "[']" nil
                         ("-B" "-d" "american")
                         nil iso-8859-1)))
          `((nil ,@default)
            ("american" ,@default))))
  (setq ispell-extra-args '("--sug-mode=ultra"))
  (setq ispell-personal-dictionary "~/.aspell.en.pws")
  (setq flyspell-issue-message-flag nil)
  
 
;; More efforts to speed up flyspell
;; See http://www.brool.com/index.php/speeding-up-flyspell-region 
  (defadvice flyspell-region (around fast-flyspell-region)
    (cl-flet ( (sit-for (x) t) ) 
      ad-do-it))
  (ad-activate 'flyspell-region)
  
#+end_src

#+RESULTS:
: flyspell-region

* My Spelling set up 

** Emacs Wiki tips

Emacs has an ispell package that interfaces to a range of spelling programs which do the heavy lifting. So =ispell.el= acts as a facade for various command line spelling utilities like =ispell=, =aspell= and =hunspell=. 

=ispell.el= has built-in support for detecting Hunspell's default dictionary so it should work out fo the box with no Emacs configuration.

Note the key variable: 

#+BEGIN_EXAMPLE
ispell-hunspell-dict-paths-alist is a variable defined in
ispell.el.gz.

Value
(("american" "/usr/share/hunspell/en_US.aff")
 ("castellano" "/usr/share/hunspell/es_ES.aff")
 ("castellano8" "/usr/share/hunspell/es_ES.aff")
 ("english" "/usr/share/hunspell/en_US.aff")
 ("es_CR" "/usr/share/hunspell/es_CR.aff")
...
 ("en_US" "/usr/share/hunspell/en_US.aff")
...
 ("es_DO" "/usr/share/hunspell/es_DO.aff")
 ("es_ES" "/usr/share/hunspell/es_ES.aff")
  ("es_CU" "/usr/share/hunspell/es_CU.aff"))
#+END_EXAMPLE

Tell ispell that apostrophes are part of words and select American English dictionary (nil). DGM changed spanish to "Castellano". And deleted this 

#+BEGIN_EXAMPLE
        ("american"
         "[[:alpha:]]"
         "[^[:alpha:]]"
         "[']"
         t
         ("-d" "en_US")
         nil
         utf-8)
#+END_EXAMPLE


#+BEGIN_SRC emacs-lisp :tangle yes
(setq ispell-local-dictionary-alist
      `((nil
         "[[:alpha:]]"
         "[^[:alpha:]]"
         "[']"
         t
         ("-d" "en_US")
         nil
         utf-8)
        ("american"
         "[[:alpha:]]"
         "[^[:alpha:]]"
         "[']"
         t
         ("-d" "en_US")
         nil
         utf-8)
 	    ("castellano"
         "[[:alpha:]]"
         "[^[:alpha:]]"
         "[']"
         t
         ("-d" "es_ES")
         nil
         utf-8)
	    ))

;; (setq ispell-program-name "hunspell")
;; It works!  It works!  After two hours of slogging, it works!
(if (file-exists-p "/usr/bin/hunspell")
    (progn
      (setq-default ispell-program-name "hunspell")
      (setq ispell-program-name         "hunspell"
            ispell-dictionary           "american"
            ispell-local-dictionary     "american")
      (eval-after-load "ispell"
        '(progn (defun ispell-get-coding-system () 'utf-8)))))

(setq ispell-really-hunspell t)

(global-set-key (kbd "C-M-$") #'ispell-change-dictionary)
#+END_SRC

#+RESULTS:
: ispell-change-dictionary

=rw-hunspell.el= provides useful extensions to =ispell.el= for Hunspell.

#+BEGIN_SRC emacs-lisp :tangle no
(require 'rw-language-and-country-codes) 
(require 'rw-ispell)
(require 'rw-hunspell)
#+END_SRC

Customization:

#+BEGIN_SRC emacs-lisp :tangle no
(setq rw-hunspell-default-dictionary "american"
      rw-hunspell-dicpath-list (quote ("/usr/share/hunspell"))
      rw-hunspell-make-dictionary-menu t
      rw-hunspell-use-rw-ispell t
      )
#+END_SRC

#+RESULTS:
: t

* Provide 

#+BEGIN_SRC emacs-lisp :tangle yes
(provide 'starter-kit-aspell)
#+END_SRC

#+RESULTS:
: starter-kit-aspell

* Final message
#+source: message-line
#+begin_src emacs-lisp :tangle yes
  (message "Starter Kit Aspell loaded.")
#+end_src

#+RESULTS: message-line
: Starter Kit Aspell loaded.





