# -*- coding: utf-8 -*-

#+TITLE: Starter Kit Lisp
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[file:starter-kit.org][Emacs Starter Kit]].

* Starter Kit Lisp
Support for editing list dialects including [[* Emacs Lisp][Emacs Lisp]], [[* Scheme][Scheme]],
[[* Common Lisp][Common Lisp]], and [[* Clojure][Clojure]].

** Define keys
#+srcname: starter-kit-define-lisp-keys
#+begin_src emacs-lisp 
(define-key read-expression-map (kbd "TAB") 'lisp-complete-symbol)
;; (define-key lisp-mode-shared-map (kbd "C-c l") "lambda")
(define-key lisp-mode-shared-map (kbd "RET") 'reindent-then-newline-and-indent)
(define-key lisp-mode-shared-map (kbd "C-\\") 'lisp-complete-symbol)
(define-key lisp-mode-shared-map (kbd "C-c v") 'eval-buffer)
#+end_src

** Non-obtrusive parenthesis faces

I can't recall why I commented this out... previously I had used the option =:tangle no= and so I had disabled all the other snippets of code.

#+begin_src emacs-lisp
(defface esk-paren-face
   '((((class color) (background dark))
      (:foreground "grey50"))
     (((class color) (background light))
      (:foreground "grey55")))
   "Face used to dim parentheses."
   :group 'starter-kit-faces)
#+end_src

#+RESULTS:
: esk-paren-face

** Emacs Lisp

#+begin_src emacs-lisp
(add-hook 'emacs-lisp-mode-hook 'turn-on-eldoc-mode)
(add-hook 'emacs-lisp-mode-hook 'run-starter-kit-coding-hook)
(add-hook 'emacs-lisp-mode-hook 'esk-remove-elc-on-save)
;; (add-hook 'emacs-lisp-mode-hook 'idle-highlight)


(defun esk-remove-elc-on-save ()
  "If you're saving an elisp file, likely the .elc is no longer valid."
  (make-local-variable 'after-save-hook)
  (add-hook 'after-save-hook
            (lambda ()
              (if (file-exists-p (concat buffer-file-name "c"))
                  (delete-file (concat buffer-file-name "c"))))))

(font-lock-add-keywords 'emacs-lisp-mode
			'(("(\\|)" . 'esk-paren-face)))
#+end_src

From  https://github.com/matklad/.emacs.d/blob/master/rc/coding.el and https://github.com/Fuco1/smartparens/wiki/Pair-management. Not needed any more given the new =smartparens= implementation.

I move it to -text.org

#+BEGIN_SRC emacs-lisp 
;; (sp-local-pair 'emacs-lisp-mode "'" nil :actions nil) 
;; (sp-local-pair 'emacs-lisp-mode "`" nil :actions nil) 
#+END_SRC


** Clojure

#+begin_src emacs-lisp
(add-hook 'clojure-mode-hook 'run-starter-kit-coding-hook)
;; (add-hook 'clojure-mode-hook 'idle-highlight)

(font-lock-add-keywords 'clojure-mode
                        '(("(\\|)" . 'esk-paren-face)))

(defface esk-clojure-trace-face
   '((((class color) (background dark))
      (:foreground "grey50"))
     (((class color) (background light))
      (:foreground "grey55")))
   "Face used to dim parentheses."
   :group 'starter-kit-faces)

(setq esk-clojure-trace-face 'esk-clojure-trace-face)

;; This will make relevant lines stand out more in stack traces
(defun sldb-font-lock ()
  (font-lock-add-keywords nil
                          '(("[0-9]+: \\(clojure\.\\(core\\|lang\\).*\\)"
                             1 esk-clojure-trace-face)
                            ("[0-9]+: \\(java.*\\)"
                             1 esk-clojure-trace-face)
                            ("[0-9]+: \\(swank.*\\)"
                             1 esk-clojure-trace-face)
                            ("\\[\\([A-Z]+\\)\\]"
                             1 font-lock-function-name-face))))

(add-hook 'sldb-mode-hook 'sldb-font-lock)

(defun slime-jump-to-trace (&optional on)
  "Jump to the file/line that the current stack trace line references.
Only works with files in your project root's src/, not in dependencies."
  (interactive)
  (save-excursion
    (beginning-of-line)
    (search-forward-regexp "[0-9]: \\([^$(]+\\).*?\\([0-9]*\\))")
    (let ((line (string-to-number (match-string 2)))
          (ns-path (split-string (match-string 1) "\\."))
          (project-root (locate-dominating-file default-directory "src/")))
      (find-file (format "%s/src/%s.clj" project-root
                         (mapconcat 'identity ns-path "/")))
      (goto-line line))))

(eval-after-load 'slime
  '(progn
     (defalias 'sldb-toggle-details 'slime-jump-to-trace)
     (defun sldb-prune-initial-frames (frames)
       "Show all stack trace lines by default."
       frames)))

(eval-after-load 'find-file-in-project
  '(add-to-list 'ffip-patterns "*.clj"))

;; You might like this, but it's a bit disorienting at first:


(defun clojure-project (path)
  "Setup classpaths for a clojure project and starts a new SLIME session.

Kills existing SLIME session, if any."
  (interactive (list
                (ido-read-directory-name
                 "Project root: "
                 (locate-dominating-file default-directory "pom.xml"))))
  (when (get-buffer "*inferior-lisp*")
    (kill-buffer "*inferior-lisp*"))
  (add-to-list 'swank-clojure-extra-vm-args
               (format "-Dclojure.compile.path=%s"
                       (expand-file-name "target/classes/" path)))
  (setq swank-clojure-binary nil
        swank-clojure-jar-path (expand-file-name "target/dependency/" path)
        swank-clojure-extra-classpaths
        (append (mapcar (lambda (d) (expand-file-name d path))
                        '("src/" "target/classes/" "test/"))
                (let ((lib (expand-file-name "lib" path)))
                  (if (file-exists-p lib)
                      (directory-files lib t ".jar$"))))
        slime-lisp-implementations
        (cons `(clojure ,(swank-clojure-cmd) :init swank-clojure-init)
              (remove-if #'(lambda (x) (eq (car x) 'clojure))
                         slime-lisp-implementations)))
  (save-window-excursion
    (slime)))
#+end_src

Prettier function names in clojure -- Thanks to Paul Hobbs for the
idea to extend this feature beyond simply the =fn= function.
#+begin_src emacs-lisp
  ;; symbols for some overlong function names
  (eval-after-load 'clojure-mode
    '(font-lock-add-keywords
      'clojure-mode
      (mapcar
       (lambda (pair)
         `(,(car pair)
           (0 (progn (compose-region
                      (match-beginning 0) (match-end 0)
                      ,(cadr pair))
                     nil))))
       '(("\\<fn\\>" ?ƒ)
         ("\\<comp\\>" ?∘)
         ("\\<partial\\>" ?þ)
         ("\\<complement\\>" ?¬)))))
#+end_src

** Scheme

From http://coldnew.github.io/coldnew-emacs/#orgheadline284

#+BEGIN_SRC emacs-lisp
;;(use-package scheme
;;  :mode ("\\.scm\\'" . scheme-mode))

;;(add-hook 'scheme-mode-hook 'geiser-mode)
#+END_SRC


#+begin_src emacs-lisp
;;(add-hook 'scheme-mode-hook 'run-starter-kit-coding-hook)
;; ;; (add-hook 'scheme-mode-hook 'idle-highlight)
;;(font-lock-add-keywords 'scheme-mode
;;			'(("(\\|)" . 'esk-paren-face)))
#+end_src


** Common Lisp

#+begin_src emacs-lisp
(add-hook 'lisp-mode-hook 'run-starter-kit-coding-hook)
;; (add-hook 'lisp-mode-hook 'idle-highlight)
(font-lock-add-keywords 'lisp-mode
			'(("(\\|)" . 'esk-paren-face)))
#+end_src

#+RESULTS:

** Racket
Starting to use Racket now, mainly for programming paradigms class, though I'm looking forward to some “REPL-driven development” whenever I get the chance.
Turned off as it seems Geiser works better.

#+BEGIN_SRC emacs-lisp 
(use-package racket-mode
  :ensure t
  :commands racket-mode
  :mode 
  ("\\.rkt[dl]?\\'" . racket-mode) ;; to enable racket-mode when I open a .rkt file. See http://coldnew.github.io/coldnew-emacs/#orgheadline1
  :config 
  (setq racket-smart-open-bracket-enable t))
#+END_SRC


Configuration that I've copied from above and applied to racket:

#+BEGIN_SRC emacs-lisp 
(add-hook 'racket-mode-hook 'run-starter-kit-coding-hook)
;; (add-hook 'racket-mode-hook 'idle-highlight)
(font-lock-add-keywords 'lisp-mode
			'(("(\\|)" . 'esk-paren-face)))

#+END_SRC

#+RESULTS:


Configuration from https://github.com/greghendershott/racket-mode 

#+BEGIN_SRC emacs-lisp 
(add-hook 'racket-mode-hook      #'racket-unicode-input-method-enable)
(add-hook 'racket-repl-mode-hook #'racket-unicode-input-method-enable)
#+END_SRC

#+RESULTS:
| racket-unicode-input-method-enable |

In the Git of racket-mode at https://github.com/greghendershott/racket-mode they propose this binding, but why? Already =C-c C-c= does the job of =racket-run=.

#+BEGIN_SRC emacs-lisp 
;;(add-hook 'racket-mode-hook
;;          (lambda ()
;;            (define-key racket-mode-map (kbd "C-c r") 'racket-run)))
#+END_SRC

From  https://github.com/matklad/.emacs.d/blob/master/rc/coding.el and https://github.com/Fuco1/smartparens/wiki/Pair-management but the new implementation of =smartparens= make this redundant. 

Moved to -text.org

#+BEGIN_SRC emacs-lisp 
;; (sp-local-pair 'racket-mode "'" nil :actions nil) 
;; (sp-local-pair 'racket-mode "`" nil :actions nil)
#+END_SRC


** Geiser
On opening a scheme file, Geiser will try to guess its Scheme,  defaulting to the first in the list. Use `C-c C-s' to select the implementation by hand (on a per file basis). From http://coldnew.github.io/coldnew-emacs/#orgheadline284

From http://www.maxxcan.com/racket-en-emacs/ I get it that =geiser= is the way of using racket inside org

#+BEGIN_SRC emacs-lisp
;;(use-package geiser
;;  :ensure t
;;  :defer t
;;  :config
;;  (setq geiser-active-implementations '(racket chicken guile)) 
;;  (setq geiser-default-implementation '(racket)))
#+END_SRC

#+RESULTS:
: t


* Final message

#+source: message-line
#+begin_src emacs-lisp
  (message "Starter Kit Lisp loaded.")
#+end_src











